export enum Paths {
  Home = '/',
  Blog = '/blog',
  SingleBlog = '/blog',
  EditBlog = '/edit/blog',
  CreateBlog = '/create/blog',
  Experience = '/experience',
  SingleExperience = '/experience',
  CreateExperience = '/create/experience',
  Profile = '/profile',
  Itinerary = '/itinerary',
  SingleItinerary = '/itinerary',
  CreateItinerary = '/create/itinerary',
  EditItinerary = '/edit/itinerary',
}
