export enum Paths {
  Home = '/',
  Blog = '/blog',
  SingleBlog = '/blog',
  EditBlog = '/edit/blog',
  CreateBlog = '/create/blog',
  Experience = '/experience',
  SingleExperience = '/experience',
  CreateExperience = '/create/experience',
  Profile = '/profile',
  Trip = '/trip',
  SingleTrip = '/trip',
  CreateTrip = '/create/trip',
  EditTrip = '/edit/trip',
}
